[project]
name = "gps-cavcrosby"
version = "1.0.0"
description = "Scripts that I use on a daily basis or find useful"
requires-python = ">=3.9,<3.10"

[[authors]]
name = "Conner Crosby"
email = "cavcrosby@gmail.com"

[license]
file = "./LICENSE"

[tool.black]
line-length = 79
